const $=s=>document.querySelector(s);let DATA=[],THEMES={},current=null,selectedCell=null,state={},display={showIds:false,compact:false,highlightKnown:false,allowRepeats:false,showFlow:false};
const key=(s,f)=>`${s}||${f}`;const stateKey=l=>`pp-themed-preview-state-${l}`;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function rich(s){let x=esc(s);x=x.replace(/&lt;color=&quot;(#[0-9A-Fa-f]{6})&quot;&gt;/g,'<span style="color:$1;font-weight:750">').replace(/&lt;\/color&gt;/g,'</span>');x=x.replace(/&lt;b&gt;/g,'<b>').replace(/&lt;\/b&gt;/g,'</b>').replace(/&lt;u&gt;/g,'<u>').replace(/&lt;\/u&gt;/g,'</u>');x=x.replace(/&lt;sprite name\s*=\s*&quot;([^&]+)&quot;&gt;/g,'<span class="sprite-token" title="$1">◆</span>');return x.replace(/\\n/g,'<br>')}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
function loadState(){try{state=JSON.parse(localStorage.getItem(stateKey(current.level))||'{}')}catch{state={}}}
function saveState(){localStorage.setItem(stateKey(current.level),JSON.stringify(state));updateProgress()}
function filteredLevels(){const theme=$('#themeSelect').value,q=$('#levelSearch').value.trim().toLowerCase();return DATA.filter(l=>(!theme||l.theme===theme)&&(!q||`${l.level} ${l.levelId} ${l.theme} ${l.caseTitle} ${l.contentGroup} ${l.subjects.join(' ')} ${l.fields.join(' ')}`.toLowerCase().includes(q)))}
function refreshLevelSelect(keep=true){const list=filteredLevels(),sel=$('#levelSelect'),wanted=keep&&current?current.level:null;sel.innerHTML=list.map(l=>`<option value="${l.level}">L${l.level} · ${esc(l.theme)} · ${esc(l.caseTitle)}</option>`).join('');if(!list.length){sel.innerHTML='<option>No matching level</option>';return}const next=list.some(l=>l.level===wanted)?wanted:list[0].level;sel.value=next;if(!current||current.level!==next)openLevel(next)}
function initControls(){const ts=$('#themeSelect');Object.values(THEMES).sort((a,b)=>a.chapter-b.chapter).forEach(t=>{const o=document.createElement('option');o.value=t.theme;o.textContent=`Chapter ${t.chapter} · ${t.theme}`;ts.appendChild(o)});ts.onchange=()=>refreshLevelSelect(false);$('#levelSearch').oninput=()=>refreshLevelSelect(false);$('#levelSelect').onchange=e=>openLevel(+e.target.value);$('#prevBtn').onclick=()=>{const list=filteredLevels();const i=list.findIndex(x=>x.level===current.level);if(i>0)openLevel(list[i-1].level)};$('#nextBtn').onclick=()=>{const list=filteredLevels();const i=list.findIndex(x=>x.level===current.level);if(i>=0&&i<list.length-1)openLevel(list[i+1].level)}}
function openLevel(n){current=DATA.find(x=>x.level===+n)||DATA[0];selectedCell=null;loadState();const sel=$('#levelSelect');if([...sel.options].some(o=>+o.value===current.level))sel.value=current.level;history.replaceState(null,'',`${location.pathname}?level=${current.level}`);renderAll()}
function renderAll(){renderMeta();renderClues();renderGrid();renderPool();renderInspector();clearResult()}
function renderMeta(){
 $('#gameLevel').textContent=`CHAPTER ${current.chapter} · LEVEL ${current.level}`;$('#gameCategory').textContent=current.theme;$('#gameCaseTitle').textContent=current.caseTitle;$('#gameQuestion').textContent=current.playerQuestion;$('#clueTitle').textContent=current.contentGroup;$('#clueCount').textContent=current.clues.length;$('#caseTheme').textContent=`Chapter ${current.chapter} · ${current.theme}`;$('#caseTitle').textContent=current.caseTitle;$('#caseQuestion').textContent=current.playerQuestion;$('#chapterStory').textContent=current.chapterStory;$('#revealText').textContent=current.finalReveal;
 const role=$('#roleBadge');role.textContent=current.chapterRole||'Level';role.className=`badge ${(current.chapterRole||'').toLowerCase()}`;$('#solutionBadge').textContent=current.uniqueSolution==='PASS'?'Unique solution PASS':'Review solution';
}
function renderClues(){const el=$('#clueList');el.innerHTML=current.clues.map((c,i)=>`<article class="clue-card"><div class="clue-top"><span class="clue-num">${i+1}</span><span class="operator-tag">${esc(c.operator)}</span><span class="field-tag">${esc(c.field)}</span></div><div class="clue-text">${rich(c.richText||c.text)}</div>${display.showFlow?`<div class="flow-card"><strong>Deduction:</strong> ${esc(c.action)}<br><strong>Outcome:</strong> ${esc(c.solveOutcome)}${c.dependency?`<br><strong>Dependency:</strong> ${esc(c.dependency)}`:''}</div>`:''}</article>`).join('')||'<div class="empty-pool">No clues found.</div>'}
function renderGrid(){const grid=$('#profileGrid');grid.className='profile-grid'+(display.compact?' compact':'');grid.style.setProperty('--cols',current.subjects.length);let html=`<div class="grid-row"><div class="grid-cell field-label">${esc(current.subjectType||'PROFILE')}</div>${current.subjects.map(s=>`<div class="grid-cell subject-cell">${esc(s)}</div>`).join('')}</div>`;current.fields.forEach((f,fi)=>{html+=`<div class="grid-row"><div class="grid-cell field-label">${esc(f)}</div>`;current.subjects.forEach((s,si)=>{const k=key(s,f),v=state[k]||'',known=current.knownAnswers[k]!=null,multi=v.includes(' / ');html+=`<button class="grid-cell target ${v?'filled':''} ${selectedCell===k?'selected':''} ${display.highlightKnown&&known?'known':''}" data-key="${esc(k)}" data-field="${esc(f)}" data-subject="${esc(s)}" data-fi="${fi}" data-si="${si}">${v?esc(v):'<span style="color:#b1b8c5;font-weight:600">Drop value</span>'}${display.showIds?`<small class="cell-id">${fi+1}.${si+1}</small>`:''}${multi?'<small class="multi-mark">MULTI</small>':''}</button>`});html+='</div>'});grid.innerHTML=html;grid.querySelectorAll('.target').forEach(c=>{c.onclick=()=>{selectedCell=c.dataset.key;renderGrid();renderPool()};c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();assign(c.dataset.key,e.dataTransfer.getData('text/plain'))}});updateProgress()}
function renderPool(){const field=selectedCell?selectedCell.split('||')[1]:null;$('#selectedField').textContent=field||'Choose a cell';const pool=$('#valuePool');if(!field){pool.innerHTML='<div class="empty-pool">Select a grid cell to show available values.</div>';return}const vals=current.options[field]||[],used=new Set(Object.entries(state).filter(([k,v])=>k.endsWith(`||${field}`)&&v).map(([,v])=>v));pool.innerHTML=vals.map(v=>`<button draggable="true" class="value-chip ${used.has(v)?'used':''}" data-value="${esc(v)}">${esc(v)}</button>`).join('');pool.querySelectorAll('.value-chip').forEach(ch=>{ch.onclick=()=>assign(selectedCell,ch.dataset.value);ch.ondragstart=e=>e.dataTransfer.setData('text/plain',ch.dataset.value)})}
function assign(k,v){if(!k||!v)return;const field=k.split('||')[1];if(!display.allowRepeats){Object.keys(state).forEach(other=>{if(other!==k&&other.endsWith(`||${field}`)&&state[other]===v)delete state[other]})}state[k]=v;saveState();renderGrid();renderPool();clearResult()}
function updateProgress(){const filled=Object.values(state).filter(Boolean).length,total=current?.stats.cells||1;$('#progressBar').style.width=`${Math.round(filled/total*100)}%`}
function clearResult(){const r=$('#resultBanner');r.className='result-banner';r.textContent='';$('#revealCard').classList.remove('show');document.querySelectorAll('.correct,.incorrect').forEach(x=>x.classList.remove('correct','incorrect'))}
function checkLevel(){clearResult();let correct=0,wrong=0,empty=0;document.querySelectorAll('.target').forEach(c=>{const k=c.dataset.key,v=state[k],answer=current.knownAnswers[k];if(!v)empty++;else if(v===answer){correct++;c.classList.add('correct')}else{wrong++;c.classList.add('incorrect')}});const r=$('#resultBanner');if(wrong===0&&empty===0){r.className='result-banner show success';r.textContent='Level complete — all answers are correct.';$('#revealCard').classList.add('show')}else{r.className=`result-banner show ${wrong?'error':'info'}`;r.textContent=`${correct} correct · ${wrong} incorrect · ${empty} empty`}}
function renderInspector(){const s=current.stats;$('#statsGrid').innerHTML=[['Clues',s.clues],['Profiles',s.subjects],['Fields',s.fields],['Cells',s.cells],['Multi cells',s.multiValueCells],['Chapter',current.chapter]].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const meta=[['Level ID',current.levelId],['Role',current.chapterRole],['Source difficulty',current.sourceDifficulty],['Geometry',current.sourceGeometry],['Logic pattern',current.logicPatternMix],['Logic identity',current.logicIdentity],['Validation',current.uniqueSolution],['Background',current.backgroundScene]];$('#metaList').innerHTML=meta.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v||'—')}</dd></div>`).join('');const art=[['Art risk',current.artRisk],['Review status',current.artReviewStatus],['Reusable assets',current.assetReuse],['New asset scope',current.newAssetScope]];$('#artList').innerHTML=art.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v||'—')}</dd></div>`).join('');$('#showIds').checked=display.showIds;$('#compactGrid').checked=display.compact;$('#highlightKnown').checked=display.highlightKnown;$('#allowRepeats').checked=display.allowRepeats;$('#showFlow').checked=display.showFlow}
function reveal(){state={...current.knownAnswers};saveState();renderGrid();renderPool();const r=$('#resultBanner');r.className='result-banner show info';r.textContent='Full solution revealed for QA testing.';$('#revealCard').classList.add('show')}
function exportState(){const payload={app:'Perfect Profile Theme Level Preview',version:2,exportedAt:new Date().toISOString(),level:current.level,states:{}};DATA.forEach(l=>{const s=localStorage.getItem(stateKey(l.level));if(s)payload.states[l.level]=JSON.parse(s)});const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='perfect-profile-themed-preview-progress.json';a.click();URL.revokeObjectURL(u)}
async function boot(){const embedded=document.querySelector('#embeddedLevelData');let raw;if(embedded){raw=JSON.parse(embedded.textContent)}else{const res=await fetch('data/levels.json');if(!res.ok)throw new Error(`HTTP ${res.status} loading data/levels.json`);raw=await res.json()}DATA=raw.levels;THEMES=Object.fromEntries(Object.entries(raw.themes||{}).map(([name,v])=>[name,{...v,theme:name}]));initControls();refreshLevelSelect(false);const n=+(new URLSearchParams(location.search).get('level')||1);openLevel(DATA.some(x=>x.level===n)?n:1);
 $('#checkBtn').onclick=checkLevel;$('#resetBtn').onclick=()=>{state={};saveState();renderGrid();renderPool();clearResult()};$('#clearCellBtn').onclick=()=>{if(selectedCell){delete state[selectedCell];saveState();renderGrid();renderPool();clearResult()}};$('#revealBtn').onclick=reveal;$('#clearProgressBtn').onclick=()=>{if(confirm('Clear saved progress for all 100 levels?')){DATA.forEach(l=>localStorage.removeItem(stateKey(l.level)));state={};renderAll();toast('All saved progress cleared')}};
 $('#showIds').onchange=e=>{display.showIds=e.target.checked;renderGrid()};$('#compactGrid').onchange=e=>{display.compact=e.target.checked;renderGrid()};$('#highlightKnown').onchange=e=>{display.highlightKnown=e.target.checked;renderGrid()};$('#allowRepeats').onchange=e=>{display.allowRepeats=e.target.checked;renderPool()};$('#showFlow').onchange=e=>{display.showFlow=e.target.checked;renderClues()};
 $('#copyLinkBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Level link copied')}catch{toast('Copy failed — copy the browser URL')}};$('#exportBtn').onclick=exportState;$('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=JSON.parse(await f.text());Object.entries(p.states||{}).forEach(([l,v])=>localStorage.setItem(stateKey(l),JSON.stringify(v)));openLevel(p.level||current.level);toast('Progress imported')}catch{toast('Invalid JSON file')}};
}
boot().catch(err=>{document.body.innerHTML=`<pre style="padding:20px;white-space:pre-wrap">Could not load level data. Upload the whole folder to GitHub Pages, or open standalone-preview.html instead.\n\n${esc(err.message)}</pre>`})
