
const $=s=>document.querySelector(s);let DATA=[],THEMES={},current=null,selectedCell=null,state=null;let display={showIds:false,compact:false,showAllCards:false,showFlow:false,autoPopup:true};let ui={wrongKey:null,successKey:null,newClues:new Set(),recentCompleted:new Set()};
const key=(s,f)=>`${s}||${f}`,storageKey=l=>`pp-spatial-preview-v3-${l}`;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function rich(s){let x=esc(s);x=x.replace(/&lt;color=&quot;(#[0-9A-Fa-f]{6})&quot;&gt;/g,'<span style="color:$1;font-weight:800">').replace(/&lt;\/color&gt;/g,'</span>').replace(/&lt;b&gt;/g,'<b>').replace(/&lt;\/b&gt;/g,'</b>').replace(/&lt;u&gt;/g,'<u>').replace(/&lt;\/u&gt;/g,'</u>').replace(/&lt;sprite name\s*=\s*&quot;([^&]+)&quot;&gt;/g,'<span class="sprite-token" title="$1">◆</span>');return x.replace(/\\n/g,'<br>')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.classList.remove('show'),1600)}
function initialState(){return{cells:{},lives:current.revealModel.lives,visibleClues:current.clues.filter(c=>c.initiallyVisible).map(c=>c.id),completedClues:[],events:[],finished:false}}
function loadState(){try{const raw=JSON.parse(localStorage.getItem(storageKey(current.level))||'null');state=raw&&raw.cells?raw:initialState()}catch{state=initialState()}state.visibleClues=[...new Set([...(state.visibleClues||[]),...current.clues.filter(c=>c.initiallyVisible).map(c=>c.id)])];state.completedClues=state.completedClues||[];state.events=state.events||[];if(state.lives==null)state.lives=2}
function saveState(){localStorage.setItem(storageKey(current.level),JSON.stringify(state))}
function logEvent(type,text){state.events.unshift({type,text,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})});state.events=state.events.slice(0,60);saveState();renderEventLog()}
function filtered(){const theme=$('#themeSelect').value,q=$('#levelSearch').value.trim().toLowerCase();return DATA.filter(l=>(!theme||l.theme===theme)&&(!q||`${l.level} ${l.levelId} ${l.theme} ${l.caseTitle} ${l.contentGroup} ${l.subjects.join(' ')} ${l.fields.join(' ')}`.toLowerCase().includes(q)))}
function refreshSelect(keep=true){const list=filtered(),sel=$('#levelSelect'),wanted=keep&&current?current.level:null;sel.innerHTML=list.map(l=>`<option value="${l.level}">L${l.level} · ${esc(l.theme)} · ${esc(l.caseTitle)}</option>`).join('');if(!list.length)return;const n=list.some(x=>x.level===wanted)?wanted:list[0].level;sel.value=n;if(!current||current.level!==n)openLevel(n)}
function initControls(){Object.entries(THEMES).sort((a,b)=>a[1].chapter-b[1].chapter).forEach(([name,t])=>$('#themeSelect').insertAdjacentHTML('beforeend',`<option value="${esc(name)}">Chapter ${t.chapter} · ${esc(name)}</option>`));$('#themeSelect').onchange=()=>refreshSelect(false);$('#levelSearch').oninput=()=>refreshSelect(false);$('#levelSelect').onchange=e=>openLevel(+e.target.value);$('#prevBtn').onclick=()=>{const a=filtered(),i=a.findIndex(x=>x.level===current.level);if(i>0)openLevel(a[i-1].level)};$('#nextBtn').onclick=()=>{const a=filtered(),i=a.findIndex(x=>x.level===current.level);if(i<a.length-1)openLevel(a[i+1].level)}}
function openLevel(n){current=DATA.find(x=>x.level===+n)||DATA[0];selectedCell=null;ui={wrongKey:null,successKey:null,newClues:new Set(),recentCompleted:new Set()};loadState();if([...$('#levelSelect').options].some(o=>+o.value===current.level))$('#levelSelect').value=current.level;history.replaceState(null,'',`${location.pathname}?level=${current.level}`);renderAll()}
function renderAll(){renderMeta();renderGrid();renderPool();renderClues();renderGameTray();renderInspector();renderHUD();renderEventLog()}
function renderMeta(){$('#gameLevel').textContent=`CHAPTER ${current.chapter} · LEVEL ${current.level}`;$('#gameCategory').textContent=current.theme;$('#gameCaseTitle').textContent=current.caseTitle;$('#gameQuestion').textContent=current.playerQuestion;$('#clueTitle').textContent=current.contentGroup;$('#caseTheme').textContent=`Chapter ${current.chapter} · ${current.theme}`;$('#caseTitle').textContent=current.caseTitle;$('#caseQuestion').textContent=current.playerQuestion;$('#chapterStory').textContent=current.chapterStory||'';const r=$('#roleBadge');r.textContent=current.chapterRole;r.className=`badge ${(current.chapterRole||'').toLowerCase()}`;$('#solutionBadge').textContent=`${current.uniqueSolution} · ${current.validationGate||'PASS'}`}
function statusOf(c){if(state.completedClues.includes(c.id))return'completed';if(state.visibleClues.includes(c.id))return'active';return'hidden'}
function renderClues(){const el=$('#clueList');let clues=current.clues;if(!display.showAllCards)clues=clues.filter(c=>statusOf(c)!=='hidden');el.innerHTML=clues.map(c=>{const st=statusOf(c),unlock=c.unlockCondition||{};return`<article class="clue-card ${st} ${ui.newClues.has(c.id)?'new':''}"><div class="clue-top"><span class="clue-num">${c.no}</span><span class="operator-tag">${esc(c.operator)}</span><span class="field-tag">${esc(c.field)}</span><span class="state-tag">${st==='completed'?'✓ DONE':st==='active'?'ACTIVE':'🔒 HIDDEN'}</span></div><div class="clue-text">${st==='hidden'&&!display.showAllCards?'Hidden clue':rich(c.richText||c.text)}</div>${display.showFlow?`<div class="flow-card"><b>Completion:</b> ${(c.involvedCells||[]).map(esc).join(', ')||'field resolved'}<br><b>Unlock:</b> ${esc(unlock.label||unlock.type)} · phase ${c.phase} · progress ${c.requiredProgress}<br><b>Policy:</b> ${esc(c.revealPolicy)}<br><b>Deduction:</b> ${esc(c.action||'')}</div>`:''}</article>`}).join('')||'<div class="empty-pool">No active clues.</div>';updateCounts()}
function renderGrid(){const g=$('#profileGrid');g.className='profile-grid'+(display.compact?' compact':'');g.style.setProperty('--cols',current.subjects.length);let h=`<div class="grid-row"><div class="grid-cell field-label">${esc(current.subjectType||'PROFILE')}</div>${current.subjects.map(s=>`<div class="grid-cell subject-cell">${esc(s)}</div>`).join('')}</div>`;current.fields.forEach((f,fi)=>{h+=`<div class="grid-row"><div class="grid-cell field-label">${esc(f)}</div>`;current.subjects.forEach((s,si)=>{const k=key(s,f),v=state.cells[k]||'';h+=`<button class="grid-cell target ${v?'filled':''} ${selectedCell===k?'selected':''} ${ui.successKey===k?'just-correct':''} ${ui.wrongKey===k?'wrong-flash':''}" data-key="${esc(k)}" data-field="${esc(f)}">${v?esc(v):'<span style="color:#a5adb8">Drop value</span>'}${display.showIds?`<small class="cell-id">${fi+1}.${si+1}</small>`:''}</button>`});h+='</div>'});g.innerHTML=h;g.querySelectorAll('.target').forEach(c=>{c.onclick=()=>{selectedCell=c.dataset.key;renderGrid();renderPool()};c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();place(c.dataset.key,e.dataTransfer.getData('text/plain'))}})}
function renderPool(){const field=selectedCell?selectedCell.split('||')[1]:null;$('#selectedField').textContent=field||'Choose a cell';if(!field){$('#valuePool').innerHTML='<div class="empty-pool">Select a grid cell to show its values.</div>';return}const used=new Set(Object.entries(state.cells).filter(([k,v])=>k.endsWith(`||${field}`)&&v).map(([,v])=>v));$('#valuePool').innerHTML=(current.options[field]||[]).map(v=>`<button draggable="true" class="value-chip ${used.has(v)?'used':''}" data-value="${esc(v)}">${esc(v)}</button>`).join('');document.querySelectorAll('.value-chip').forEach(b=>{b.onclick=()=>place(selectedCell,b.dataset.value);b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.value)})}
function correctCount(){return Object.entries(state.cells).filter(([k,v])=>current.knownAnswers[k]===v).length}
function completionSatisfied(c){return (c.involvedCells||[]).length>0&&(c.involvedCells||[]).every(k=>state.cells[k]===current.knownAnswers[k])}
function unlockSatisfied(c,ignoreProgress=false){const u=c.unlockCondition||{};let ok=u.type==='initial';if(u.type==='fact_resolved')ok=state.cells[u.cell]===current.knownAnswers[u.cell];if(u.type==='clue_completed')ok=state.completedClues.includes(u.clueId);return ok&&(ignoreProgress||correctCount()>=Number(c.requiredProgress||0))}
function place(k,v){if(!k||!v||state.finished)return;if(state.lives<=0){showOutOfLives();return}const answer=current.knownAnswers[k];if(v!==answer){state.lives=Math.max(0,state.lives-1);ui.wrongKey=k;logEvent('wrong',`Wrong: ${v} → ${k}. Life -1.`);saveState();renderHUD();renderGrid();setTimeout(()=>{ui.wrongKey=null;renderGrid();if(state.lives===0)showOutOfLives()},520);return}const field=k.split('||')[1];Object.keys(state.cells).forEach(other=>{if(other!==k&&other.endsWith(`||${field}`)&&state.cells[other]===v)delete state.cells[other]});state.cells[k]=v;ui.successKey=k;logEvent('correct',`Correct: ${v} → ${k}.`);saveState();renderGrid();renderPool();renderHUD();setTimeout(()=>{ui.successKey=null;renderGrid()},720);evaluateAfterCorrect()}
function evaluateAfterCorrect(){const newly=current.clues.filter(c=>state.visibleClues.includes(c.id)&&!state.completedClues.includes(c.id)&&completionSatisfied(c));if(newly.length){newly.forEach(c=>{state.completedClues.push(c.id);ui.recentCompleted.add(c.id);logEvent('clue_complete',`Clue ${c.no} completed: ${c.text}`)});saveState();renderClues();renderGameTray();setTimeout(()=>{newly.forEach(c=>ui.recentCompleted.delete(c.id));revealEligible();renderClues();renderGameTray()},850)}else revealEligible();if(correctCount()===current.stats.cells)completeLevel()}
function revealEligible(manual=false){const hidden=current.clues.filter(c=>!state.visibleClues.includes(c.id));let eligible=hidden.filter(c=>manual?true:unlockSatisfied(c));if(!eligible.length){renderGameTray();return false}eligible.sort((a,b)=>a.phase-b.phase||a.priority-b.priority);const first=eligible[0],same=eligible.filter(c=>c.revealBatchGroup===first.revealBatchGroup);const batch=(same.length>1?same:eligible).slice(0,current.revealModel.revealBatchSize||2);batch.forEach(c=>{state.visibleClues.push(c.id);ui.newClues.add(c.id);logEvent('clue_reveal',`${manual?'Manual reveal':'New clue'} ${c.no}: ${c.text}`)});saveState();renderClues();renderGameTray();if(display.autoPopup)showNewClueModal(batch,manual);setTimeout(()=>{batch.forEach(c=>ui.newClues.delete(c.id));renderClues();renderGameTray();if(batch.some(completionSatisfied))evaluateAfterCorrect()},1200);return true}
function renderGameTray(){const tray=$('#gameClueTray');const visible=current.clues.filter(c=>state.visibleClues.includes(c.id));let active=visible.filter(c=>!state.completedClues.includes(c.id));let recent=visible.filter(c=>ui.recentCompleted.has(c.id));let cards=[...recent,...active];if(!display.showAllCards)cards=cards.slice(0,current.revealModel.maxActiveClues||4);const hidden=current.clues.some(c=>!state.visibleClues.includes(c.id));if(cards.length){tray.innerHTML=cards.map(c=>`<article class="game-clue-card ${ui.recentCompleted.has(c.id)?'completed':''} ${ui.newClues.has(c.id)?'new':''}">${ui.recentCompleted.has(c.id)?'<span class="check">✓</span>':''}${rich(c.richText||c.text)}</article>`).join('')+(hidden?'<article class="game-clue-card manual" id="trayReveal">❓<br>Reveal next clue<br><small>QA / ad preview</small></article>':'');const b=$('#trayReveal');if(b)b.onclick=()=>revealEligible(true)}else if(hidden){const progress=correctCount(),next=current.clues.find(c=>!state.visibleClues.includes(c.id));const gate=next&&progress<next.requiredProgress;tray.innerHTML=gate?`<div class="gate-message">Fill the grid to get more clues<br><small>${progress}/${next.requiredProgress} correct cells for next phase</small></div><article class="game-clue-card manual" id="trayReveal">❓<br>Reveal</article>`:'<div class="gate-message">Complete an active branch to reveal more clues.</div><article class="game-clue-card manual" id="trayReveal">❓<br>Reveal</article>';$('#trayReveal').onclick=()=>revealEligible(true)}else tray.innerHTML='<div class="gate-message">Fill the grid to complete the level</div>';updateCounts()}
function updateCounts(){const done=state.completedClues.length,total=current.clues.length;$('#gameClueCount').textContent=`Clues: ${done}/${total}`;$('#clueCountSide').textContent=`${done}/${total}`}
function renderHUD(){const hearts=Array.from({length:current.revealModel.lives},(_,i)=>`<span class="heart ${i<state.lives?'':'empty'}">♥</span>`).join('');$('#livesHud').innerHTML=`<span class="hearts">${hearts}</span>`}
function showModal(htmlContent){$('#modalCard').innerHTML=htmlContent;$('#modalLayer').classList.add('show');$('#modalLayer').setAttribute('aria-hidden','false')}
function closeModal(){$('#modalLayer').classList.remove('show');$('#modalLayer').setAttribute('aria-hidden','true')}
function showOutOfLives(){showModal(`<div class="big-icon">♡♡</div><h2>Out of Lives!</h2><p>A wrong placement flashes red, is rejected, and consumes one heart—matching the walkthrough behavior.</p><button class="primary" id="refillLives">Refill +2 lives</button>`);$('#refillLives').onclick=()=>{state.lives=current.revealModel.lives;saveState();renderHUD();logEvent('life_refill','Lives refilled for QA testing.');closeModal()}}
function showNewClueModal(batch,manual){showModal(`<div class="big-icon">❓</div><h2>${manual?'Extra Clue Unlocked!':'New Clue!'}</h2><p>${batch.length} clue${batch.length>1?'s':''} added to the tray.</p><button class="primary" id="continueClue">Continue</button>`);$('#continueClue').onclick=closeModal}
function completeLevel(){if(state.finished)return;state.finished=true;current.clues.forEach(c=>{if(!state.completedClues.includes(c.id))state.completedClues.push(c.id)});saveState();logEvent('complete','Level completed.');renderAll();showModal(`<div class="confetti">🎊✨🎉</div><h2>LEVEL COMPLETE!</h2><p>All ${current.stats.cells} cells are correct.</p><div class="final-reveal">${esc(current.finalReveal)}</div><button class="primary" id="continueLevel">Continue</button>`);$('#continueLevel').onclick=()=>{closeModal();const list=filtered(),i=list.findIndex(x=>x.level===current.level);if(i>=0&&i<list.length-1)openLevel(list[i+1].level)}}
function qaCheck(){let wrong=0,empty=0;Object.keys(current.knownAnswers).forEach(k=>{const v=state.cells[k];if(!v)empty++;else if(v!==current.knownAnswers[k])wrong++});const r=$('#resultBanner');r.className=`result-banner show ${wrong?'error':empty?'info':'success'}`;r.textContent=wrong?`${wrong} wrong · ${empty} empty`:empty?`${correctCount()} correct · ${empty} empty`:'All cells are correct.'}
function renderInspector(){const s=current.stats;$('#statsGrid').innerHTML=[['Clues',s.clues],['Profiles',s.subjects],['Fields',s.fields],['Cells',s.cells],['Correct',correctCount()],['Lives',state.lives]].map(([a,b])=>`<div class="stat-card"><span>${a}</span><strong>${b}</strong></div>`).join('');const meta=[['Level ID',current.levelId],['Role',current.chapterRole],['Geometry',current.sourceGeometry],['Logic mix',current.logicPatternMix],['Reveal model',current.revealModel.name],['Validation',current.uniqueSolution],['Art risk',current.artRisk],['Background',current.backgroundScene]];$('#metaList').innerHTML=meta.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b||'—')}</dd></div>`).join('');$('#showIds').checked=display.showIds;$('#compactGrid').checked=display.compact;$('#showAllCards').checked=display.showAllCards;$('#showFlow').checked=display.showFlow;$('#autoPopup').checked=display.autoPopup}
function renderEventLog(){$('#eventLog').innerHTML=(state.events||[]).map(e=>`<div class="event-item"><time>${esc(e.time)}</time>${esc(e.text)}</div>`).join('')||'<div class="empty-pool">No runtime events yet.</div>'}
function resetLevel(){state=initialState();saveState();selectedCell=null;ui={wrongKey:null,successKey:null,newClues:new Set(),recentCompleted:new Set()};renderAll();logEvent('reset','Level reset.')}
function autoFill(){state.cells={...current.knownAnswers};state.visibleClues=current.clues.map(c=>c.id);state.completedClues=current.clues.map(c=>c.id);saveState();renderAll();completeLevel()}
function exportProgress(){const p={app:'Perfect Profile Spatial Clue Preview',version:3,level:current.level,states:{}};DATA.forEach(l=>{const x=localStorage.getItem(storageKey(l.level));if(x)p.states[l.level]=JSON.parse(x)});const b=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='perfect-profile-preview-progress.json';a.click();URL.revokeObjectURL(u)}
async function boot(){const embedded=$('#embeddedLevelData');const raw=embedded?JSON.parse(embedded.textContent):await fetch('data/levels.json').then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()});DATA=raw.levels;THEMES=raw.themes;initControls();refreshSelect(false);const n=+(new URLSearchParams(location.search).get('level')||1);openLevel(DATA.some(x=>x.level===n)?n:1);$('#checkBtn').onclick=qaCheck;$('#resetBtn').onclick=resetLevel;$('#clearCellBtn').onclick=()=>{if(selectedCell){delete state.cells[selectedCell];saveState();renderAll()}};$('#manualRevealBtn').onclick=()=>revealEligible(true);$('#hintBtn').onclick=()=>revealEligible(true);$('#eraseBtn').onclick=()=>{if(selectedCell){delete state.cells[selectedCell];saveState();renderGrid();renderPool();renderInspector()}};$('#revealBtn').onclick=autoFill;$('#showIds').onchange=e=>{display.showIds=e.target.checked;renderGrid()};$('#compactGrid').onchange=e=>{display.compact=e.target.checked;renderGrid()};$('#showAllCards').onchange=e=>{display.showAllCards=e.target.checked;renderClues();renderGameTray()};$('#showFlow').onchange=e=>{display.showFlow=e.target.checked;renderClues()};$('#autoPopup').onchange=e=>display.autoPopup=e.target.checked;$('#copyLinkBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Level link copied')}catch{toast('Copy the browser URL manually')}};$('#exportBtn').onclick=exportProgress;$('#clearProgressBtn').onclick=()=>{if(confirm('Clear progress for all levels?')){DATA.forEach(l=>localStorage.removeItem(storageKey(l.level)));openLevel(current.level)}};$('#importInput').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());Object.entries(p.states||{}).forEach(([l,v])=>localStorage.setItem(storageKey(l),JSON.stringify(v)));openLevel(p.level||current.level);toast('Progress imported')}catch{toast('Invalid JSON')}};$('#modalLayer').onclick=e=>{if(e.target.id==='modalLayer')closeModal()}}
boot().catch(err=>document.body.innerHTML=`<pre style="padding:20px">Could not load data. Upload the whole folder, or open standalone-preview.html.\n\n${esc(err.message)}</pre>`)
